INSERT INTO produit VALUES (1, 'Souris', 'Souris Razer', 70.5)
INSERT INTO produit VALUES (2, 'Clavier', 'Clavier Logitech', 120.0)
INSERT INTO produit VALUES (3, 'Casque', 'Casque Steelseries', 90.3)
INSERT INTO produit VALUES (4, 'Ecran', 'Ecran Samsung', 500.)
INSERT INTO produit VALUES (5, 'Siège', 'Siège DXRacer', 350.5)
